
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hnc-operator-v1-namespacebinding
  failurePolicy: Fail
  name: mnamespacebinding.kb.io
  rules:
  - apiGroups:
    - hnc.operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacebindings
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hnc-operator-v1-namespacebinding
  failurePolicy: Fail
  name: vnamespacebinding.kb.io
  rules:
  - apiGroups:
    - hnc.operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacebindings
  sideEffects: None
