# permissions for end users to view namespacebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacebinding-viewer-role
rules:
- apiGroups:
  - hnc.operator
  resources:
  - namespacebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hnc.operator
  resources:
  - namespacebindings/status
  verbs:
  - get
