apiVersion: hnc.operator/v1
kind: NamespaceBinding
metadata:
  name: config
spec:
  interval: 30
  parent: sandbox
  selector: kiosk.sh/account,!sandbox.tree.hnc.x-k8s.io/depth
  exclusions:
    - value: vcluster-
